In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__


'2.0.0'

In [3]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
d = tf.where(c<0,tf.fill(c.shape,np.nan),c) 
d

<tf.Tensor: id=6, shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [4]:
#如果where只有一个参数，将返回所有满足条件的位置坐标
indices = tf.where(c<0)
indices

<tf.Tensor: id=9, shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [5]:
c

<tf.Tensor: id=0, shape=(3, 3), dtype=float32, numpy=
array([[-1.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3., -3.,  3.]], dtype=float32)>

In [6]:
a = tf.random.uniform(shape=[1,3,3,2],
                      minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[88 207]
   [116 10]
   [122 176]]

  [[36 217]
   [250 34]
   [15 14]]

  [[197 83]
   [8 94]
   [133 190]]]]


In [7]:
b = tf.reshape(a,[3,6])
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[88 207 116 10 122 176]
 [36 217 250 34 15 14]
 [197 83 8 94 133 190]]


In [8]:
c = tf.reshape(b,[1,3,3,2])
tf.print(c)

[[[[88 207]
   [116 10]
   [122 176]]

  [[36 217]
   [250 34]
   [15 14]]

  [[197 83]
   [8 94]
   [133 190]]]]


In [9]:
a

<tf.Tensor: id=13, shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[ 88, 207],
         [116,  10],
         [122, 176]],

        [[ 36, 217],
         [250,  34],
         [ 15,  14]],

        [[197,  83],
         [  8,  94],
         [133, 190]]]], dtype=int32)>

In [10]:
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[88 207]
  [116 10]
  [122 176]]

 [[36 217]
  [250 34]
  [15 14]]

 [[197 83]
  [8 94]
  [133 190]]]


In [11]:
s

<tf.Tensor: id=23, shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 88, 207],
        [116,  10],
        [122, 176]],

       [[ 36, 217],
        [250,  34],
        [ 15,  14]],

       [[197,  83],
        [  8,  94],
        [133, 190]]], dtype=int32)>

In [12]:
ss = tf.squeeze(s)
tf.print(ss.shape)
tf.print(ss)

TensorShape([3, 3, 2])
[[[88 207]
  [116 10]
  [122 176]]

 [[36 217]
  [250 34]
  [15 14]]

 [[197 83]
  [8 94]
  [133 190]]]


In [13]:
d = tf.expand_dims(s,axis=0) #在第0维插入长度为1的一个维度
d

<tf.Tensor: id=30, shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[ 88, 207],
         [116,  10],
         [122, 176]],

        [[ 36, 217],
         [250,  34],
         [ 15,  14]],

        [[197,  83],
         [  8,  94],
         [133, 190]]]], dtype=int32)>

In [14]:
dd = tf.expand_dims(s,axis=1) #在第0维插入长度为1的一个维度
dd

<tf.Tensor: id=32, shape=(3, 1, 3, 2), dtype=int32, numpy=
array([[[[ 88, 207],
         [116,  10],
         [122, 176]]],


       [[[ 36, 217],
         [250,  34],
         [ 15,  14]]],


       [[[197,  83],
         [  8,  94],
         [133, 190]]]], dtype=int32)>

In [15]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

# 转换成 Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


In [16]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)

<tf.Tensor: id=45, shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [17]:
tf.stack([a,b,c])

<tf.Tensor: id=46, shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [18]:
tf.stack([a,b,c],axis=1)

<tf.Tensor: id=47, shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]],

       [[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]], dtype=float32)>

In [19]:
tf.split(c,3,axis = 0)  #指定分割份数，平均分割

InvalidArgumentError: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 2) and num_split 3 [Op:Split] name: split

In [24]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

d = tf.concat([a,b,c],axis = 0)
d

<tf.Tensor: id=64, shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [25]:
tf.split(d,2,axis = 1)  #指定分割份数，平均分割

[<tf.Tensor: id=67, shape=(6, 1), dtype=float32, numpy=
 array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]], dtype=float32)>,
 <tf.Tensor: id=68, shape=(6, 1), dtype=float32, numpy=
 array([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.]], dtype=float32)>]

In [26]:
tf.split(d,[2,2,2],axis = 0) #指定每份的记录数量

[<tf.Tensor: id=71, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: id=72, shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: id=73, shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [27]:
a = tf.constant([[1.0,2],[-3,4.0]])
b = tf.constant([[5.0,6],[7.0,8.0]])
a+b  #运算符重载

<tf.Tensor: id=76, shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 4., 12.]], dtype=float32)>

In [28]:
a-b

<tf.Tensor: id=77, shape=(2, 2), dtype=float32, numpy=
array([[ -4.,  -4.],
       [-10.,  -4.]], dtype=float32)>

In [29]:
a*b

<tf.Tensor: id=78, shape=(2, 2), dtype=float32, numpy=
array([[  5.,  12.],
       [-21.,  32.]], dtype=float32)>

In [30]:
a/b

<tf.Tensor: id=79, shape=(2, 2), dtype=float32, numpy=
array([[ 0.2       ,  0.33333334],
       [-0.42857143,  0.5       ]], dtype=float32)>

In [31]:
a**2

<tf.Tensor: id=81, shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [32]:
a

<tf.Tensor: id=74, shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-3.,  4.]], dtype=float32)>

In [33]:
a**(0.5)

<tf.Tensor: id=83, shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>

In [34]:
a%3

<tf.Tensor: id=85, shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-0.,  1.]], dtype=float32)>

In [35]:
a//3

<tf.Tensor: id=87, shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  0.],
       [-1.,  1.]], dtype=float32)>

In [36]:
(a>=2)

<tf.Tensor: id=89, shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False,  True]])>

In [37]:
a

<tf.Tensor: id=74, shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-3.,  4.]], dtype=float32)>

In [38]:
(a>=2)&(a<=3)

<tf.Tensor: id=94, shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False]])>

In [39]:
(a>=2)|(a<=3)

<tf.Tensor: id=99, shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [40]:
a==5

<tf.Tensor: id=101, shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [41]:
tf.sqrt(a)

<tf.Tensor: id=102, shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>

In [42]:
a = tf.constant([1.0,8.0])
b = tf.constant([5.0,6.0])
c = tf.constant([6.0,7.0])
tf.add_n([a,b,c])

<tf.Tensor: id=106, shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>

In [43]:
a+b

<tf.Tensor: id=107, shape=(2,), dtype=float32, numpy=array([ 6., 14.], dtype=float32)>

In [44]:
tf.print(tf.maximum(a,b))

[5 8]


In [45]:
tf.print(tf.minimum(a,b))

[1 6]


In [63]:
a = tf.range(1,25)
a

<tf.Tensor: id=154, shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [48]:
tf.reduce_sum(a)

<tf.Tensor: id=121, shape=(), dtype=int32, numpy=45>

In [49]:
tf.reduce_mean(a)

<tf.Tensor: id=123, shape=(), dtype=int32, numpy=5>

In [50]:
tf.reduce_max(a)

<tf.Tensor: id=125, shape=(), dtype=int32, numpy=9>

In [51]:
tf.reduce_min(a)

<tf.Tensor: id=127, shape=(), dtype=int32, numpy=1>

In [52]:
tf.reduce_prod(a)

<tf.Tensor: id=129, shape=(), dtype=int32, numpy=362880>

In [69]:
#张量指定维度进行reduce
b = tf.reshape(a,(3,4,2))
b

<tf.Tensor: id=166, shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [73]:
tf.reduce_sum(b, axis=0, keepdims=True)

<tf.Tensor: id=174, shape=(1, 4, 2), dtype=int32, numpy=
array([[[27, 30],
        [33, 36],
        [39, 42],
        [45, 48]]], dtype=int32)>

In [74]:
#bool类型的reduce
p = tf.constant([True,False,False])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))  # 逻辑并
tf.print(tf.reduce_any(q))  # 逻辑或

0
1


In [75]:
a = tf.range(1,10)
tf.print(tf.math.cumsum(a))
tf.print(tf.math.cumprod(a))

[1 3 6 ... 28 36 45]
[1 2 6 ... 5040 40320 362880]


In [76]:
#arg最大最小值索引
a = tf.range(1,10)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))

8
0


In [77]:
#tf.math.top_k可以用于对张量排序
a = tf.constant([1,3,7,5,4,8])

values,indices = tf.math.top_k(a,3,sorted=True)
tf.print(values)
tf.print(indices)

#利用tf.math.top_k可以在TensorFlow中实现KNN算法

[8 7 5]
[5 2 3]


In [78]:
#矩阵乘法
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])
a@b  #等价于tf.matmul(a,b)

<tf.Tensor: id=211, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [86]:
a = tf.range(1,10)
a = tf.reshape(a, (3, 3))
a

<tf.Tensor: id=256, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [85]:
b = tf.range(1,10)
b = b[::-1]
b = tf.reshape(b, (3, 3))
b

<tf.Tensor: id=250, shape=(3, 3), dtype=int32, numpy=
array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]], dtype=int32)>

In [87]:
a@b

<tf.Tensor: id=257, shape=(3, 3), dtype=int32, numpy=
array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]], dtype=int32)>

In [88]:
tf.transpose(a)

<tf.Tensor: id=259, shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>

In [89]:
#矩阵逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0,2],[3.0,4]],dtype = tf.float32)
tf.linalg.inv(a)

<tf.Tensor: id=261, shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [90]:
#矩阵求trace 在线性代数中，一个n×n矩阵A的主对角线（从左上方至右下方的对角线）上各个元素的总和被称为矩阵A的迹（或迹数），一般记作tr(A)。
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.trace(a)

<tf.Tensor: id=265, shape=(), dtype=float32, numpy=5.0>

In [91]:
#矩阵求范数
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.norm(a)

<tf.Tensor: id=271, shape=(), dtype=float32, numpy=5.477226>

In [92]:
#矩阵行列式
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.det(a)

<tf.Tensor: id=273, shape=(), dtype=float32, numpy=-2.0>

In [93]:
#矩阵特征值
tf.linalg.eigvalsh(a)

<tf.Tensor: id=274, shape=(2,), dtype=float32, numpy=array([-0.8541021,  5.854102 ], dtype=float32)>

In [94]:
#矩阵qr分解
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227734]]
[[-3.1622777 -4.4271884]
 [0 -0.632455349]]
[[1.00000012 1.99999976]
 [3 4]]


In [95]:
#矩阵svd分解
a  = tf.constant([[1.0,2.0],[3.0,4.0]],dtype = tf.float32)
v,s,d = tf.linalg.svd(a)
tf.matmul(tf.matmul(s,tf.linalg.diag(v)),d)

<tf.Tensor: id=289, shape=(2, 2), dtype=float32, numpy=
array([[0.9999996, 1.9999996],
       [2.9999998, 4.       ]], dtype=float32)>